/* ============================================================
   ControleFinanceiroWeb - Database schema
   Firebird 3.0 / SQL dialect 3 / charset ISO8859_1

   Creates the database and its three tables. Run this before
   seed.sql. See database/README.md for instructions.
   ============================================================ */

SET SQL DIALECT 3;

CREATE DATABASE 'DATABASE.FDB'
    USER 'SYSDBA' PASSWORD 'masterkey'
    PAGE_SIZE 8192
    DEFAULT CHARACTER SET ISO8859_1;

/* ------------------------------------------------------------
   CATEGORY
   Spending and income categories. STATEMENT_IDENTIFIERS holds
   pipe-separated keywords ("UBER|99POP") matched against a
   transaction description to categorise it automatically.
   ENTRY_TYPE: 'F' = fixed monthly cost, 'V' = variable.
   ------------------------------------------------------------ */
CREATE TABLE CATEGORY (
    ID                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRIPTION           VARCHAR(255) NOT NULL,
    ENTRY_TYPE            CHAR(1) NOT NULL,
    STATEMENT_IDENTIFIERS VARCHAR(5000) NOT NULL,
    PRIMARY KEY (ID)
);

/* ------------------------------------------------------------
   STATEMENT_TYPES
   Accounts a transaction can belong to (chequing, credit card).
   ------------------------------------------------------------ */
CREATE TABLE STATEMENT_TYPES (
    ID          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID)
);

/* ------------------------------------------------------------
   STATEMENT
   Individual transactions. A positive AMOUNT is income, a
   negative one is an expense. ENTRY_ID points at CATEGORY.ID
   and is null while a transaction is uncategorised.
   ------------------------------------------------------------ */
CREATE TABLE STATEMENT (
    ID                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TRANSACTION_DATE  DATE,
    DUE_DATE          DATE,
    AMOUNT            NUMERIC(18, 2),
    DESCRIPTION       VARCHAR(255),
    ENTRY_ID          INTEGER,
    STATEMENT_TYPE_ID INTEGER,
    PRIMARY KEY (ID)
);

COMMIT;

/* ------------------------------------------------------------
   Referential integrity is currently enforced by the
   application layer only; the statements below are not applied
   so that this schema stays identical to the running database.
   Enabling them requires clearing orphan rows first.

   ALTER TABLE STATEMENT ADD CONSTRAINT FK_STATEMENT_CATEGORY
       FOREIGN KEY (ENTRY_ID) REFERENCES CATEGORY (ID);

   ALTER TABLE STATEMENT ADD CONSTRAINT FK_STATEMENT_TYPE
       FOREIGN KEY (STATEMENT_TYPE_ID) REFERENCES STATEMENT_TYPES (ID);

   CREATE INDEX IDX_STATEMENT_TRANSACTION_DATE ON STATEMENT (TRANSACTION_DATE);
   CREATE INDEX IDX_STATEMENT_DUE_DATE ON STATEMENT (DUE_DATE);
   ------------------------------------------------------------ */
