/* ============================================================
   ControleFinanceiroWeb - Demo data
   Firebird 3.0 / SQL dialect 3 / charset ISO8859_1

   Fictitious household data used to demo the application.
   Runs after schema.sql, against a database the caller already
   created and connected to. Contains no real financial records.

   Dates are relative to the current month, so the dashboard is
   always populated no matter when the database is created.
   This expression resolves to day N of the current month:

       CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + N
   ============================================================ */


/* ---------------- Accounts ---------------- */
INSERT INTO STATEMENT_TYPES (ID, DESCRIPTION) VALUES (1, 'Conta Corrente');
INSERT INTO STATEMENT_TYPES (ID, DESCRIPTION) VALUES (2, 'Cartão de Crédito');

/* ---------------- Categories ----------------
   ENTRY_TYPE: 'F' = fixed monthly cost, 'V' = variable.
   STATEMENT_IDENTIFIERS holds pipe-separated keywords matched
   against a transaction description to categorise it.          */
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (1,  'Moradia',             'F', 'ALUGUEL|CONDOMINIO|IPTU');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (2,  'Energia',             'F', 'ENERGIA|ELETRICA|LUZ');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (3,  'Água',                'F', 'AGUA|SANEAMENTO');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (4,  'Internet e Telefone', 'F', 'INTERNET|TELEFONE|BANDA LARGA|CELULAR');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (5,  'Educação',            'F', 'ESCOLA|MENSALIDADE|FACULDADE|CURSO');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (6,  'Seguros',             'F', 'SEGURO|APOLICE');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (7,  'Alimentação',         'V', 'SUPERMERCADO|MERCADO|PADARIA|ACOUGUE|HORTIFRUTI');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (8,  'Transporte',          'V', 'POSTO|COMBUSTIVEL|ESTACIONAMENTO|PEDAGIO');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (9,  'Saúde',               'V', 'FARMACIA|DROGARIA|CONSULTA|EXAME|LABORATORIO');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (10, 'Lazer',               'V', 'CINEMA|RESTAURANTE|STREAMING|LANCHONETE');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (11, 'Vestuário',           'V', 'LOJA DEPARTAMENTO|CALCADOS|CONFECCOES');
INSERT INTO CATEGORY (ID, DESCRIPTION, ENTRY_TYPE, STATEMENT_IDENTIFIERS) VALUES (12, 'Receitas',            'V', 'SALARIO|PAGAMENTO|RENDIMENTO');

/* ---------------- Income (Extrato, account 0) ---------------- */
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 5, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 5, 7850.00, 'SALARIO EMPRESA DEMO LTDA', 12, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 5, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 5, 4200.00, 'SALARIO SEGUNDA FONTE', 12, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 15, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 15, 312.47, 'RENDIMENTO APLICACAO AUTOMATICA', 12, 0);

/* ---------------- Fixed costs (Extrato, account 0) ---------------- */
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 8, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 10, -2100.00, 'PAG BOLETO CONDOMINIO EDIFICIO DEMO', 1, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 9, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 12, -287.63, 'PAG BOLETO ENERGIA ELETRICA', 2, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 9, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 12, -134.80, 'PAG BOLETO SANEAMENTO AGUA', 3, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 10, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 10, -199.90, 'DEB AUTOMATICO INTERNET BANDA LARGA', 4, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 7, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 7, -1450.00, 'PAG BOLETO ESCOLA MENSALIDADE', 5, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (NULL, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 25, -178.40, 'SEGURO RESIDENCIAL APOLICE 000123', 6, 0);

/* ---------------- Variable costs (Extrato, account 0) ---------------- */
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 3, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 3, -642.18, 'SUPERMERCADO DEMO FILIAL 04', 7, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 14, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 14, -518.92, 'SUPERMERCADO DEMO FILIAL 04', 7, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 6, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 6, -89.90, 'PADARIA CENTRAL', 7, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 4, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 4, -280.00, 'POSTO COMBUSTIVEL AVENIDA', 8, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 18, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 18, -265.00, 'POSTO COMBUSTIVEL AVENIDA', 8, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 11, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 11, -156.70, 'DROGARIA SAUDE TOTAL', 9, 0);

/* ---------------- Credit card (account 2) ---------------- */
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 2, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 20, -119.80, 'RESTAURANTE DEMO', 10, 2);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 6, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 20, -55.90, 'SERVICO STREAMING MENSAL', 10, 2);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 13, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 20, -389.90, 'LOJA DEPARTAMENTO DEMO', 11, 2);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 16, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 20, -240.00, 'CINEMA SHOPPING DEMO', 10, 2);

/* ---------------- Uncategorised, to demo the keyword matching ---------------- */
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 17, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 17, -74.30, 'HORTIFRUTI BAIRRO NOVO', NULL, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 19, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 19, -132.00, 'FARMACIA POPULAR CENTRO', NULL, 0);
INSERT INTO STATEMENT (TRANSACTION_DATE, DUE_DATE, AMOUNT, DESCRIPTION, ENTRY_ID, STATEMENT_TYPE_ID)
VALUES (CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 21, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 21, -47.50, 'ESTACIONAMENTO ROTATIVO', NULL, 0);

COMMIT;

/* The explicit IDs above do not advance the identity generators.
   Restart them so rows inserted by the application do not collide
   with the seeded primary keys. */
ALTER TABLE CATEGORY        ALTER COLUMN ID RESTART WITH 100;
ALTER TABLE STATEMENT_TYPES ALTER COLUMN ID RESTART WITH 100;

COMMIT;
